Support 5.1.0 new nginx docker image (#7)
* art-compose - Add support for upgrading with '-a upgrade'

* Changes to support 5.1.0 new Nginx Docker image with a single volume mount

diff --git a/docker-compose/art-compose b/docker-compose/art-compose
--- a/docker-compose/art-compose
+++ b/docker-compose/art-compose
@@ -8,13 +8,13 @@
 #
 ######################################################
 
-SCRIPT_DIR=$(dirname $0)
+SCRIPT_NAME=$(basename $0)
 DEFAULT_ROOT_DATA_DIR=/data
 LINUX_ROOT_DATA_DIR=${DEFAULT_ROOT_DATA_DIR}
 MAC_DEFAULT_ROOT_DATA_DIR=~/.jfrog/artifactory
 DB_DRIVER=postgresql-9.4.1212.jar
 DB_DRIVER_URL=https://jdbc.postgresql.org/download/${DB_DRIVER}
-ARTIFACTORY_VERSION=5.0.1
+ARTIFACTORY_VERSION=5.1.0
 ART_COMPOSE_YML=https://jfrog.bintray.com/run/artifactory-pro/${ARTIFACTORY_VERSION}/compose/artifactory-pro.yml
 COMPOSE_FILE=artifactory-pro.yml
 DB_PASSWORD_FILE=.dbpassword
@@ -28,11 +28,11 @@ usage () {
 
     cat << END_USAGE
 
-$0 - script for starting up an Artifactory Pro with Docker compose
+$SCRIPT_NAME - script for starting and controlling an Artifactory Pro instance with Docker compose
 
-Usage: $0 <options>
+Usage: ./$SCRIPT_NAME <options>
 Supported options
--a   : Action to run. start, stop, restart, status, remove, logs (defaults to start)
+-a   : Action to run. start, stop, restart, status, upgrade, remove, logs (defaults to start)
 -d   : Custom root data directory (defaults to $DEFAULT_ROOT_DATA_DIR on Linux and $MAC_DEFAULT_ROOT_DATA_DIR on Mac)
 -c   : Clean local data directory. Delete the data directory on the host before creating the new ones
 -f   : Force removal if -c is passed (do not prompt)
@@ -40,9 +40,10 @@ Supported options
 
 Examples
 Prepare directories for Artifactory pro with default data directory
-Start  : sudo $0 -a start -c
-Stop   : sudo $0 -a stop
-Status : sudo $0 -a status
+Start   : sudo ./$SCRIPT_NAME -a start -c
+Stop    : sudo ./$SCRIPT_NAME -a stop
+Status  : sudo ./$SCRIPT_NAME -a status
+Upgrade : sudo ./$SCRIPT_NAME -a upgrade
 
 END_USAGE
 
@@ -73,7 +74,7 @@ processOptions() {
         case $opt in
             a)  # Action
                 ACTION=$OPTARG
-                [[ "$ACTION" =~ ^(start|stop|restart|status|remove|logs)$ ]] || usage
+                [[ "$ACTION" =~ ^(start|stop|restart|status|upgrade|remove|logs)$ ]] || usage
             ;;
             d)  # Data dir
                 ROOT_DATA_DIR=$OPTARG
@@ -108,6 +109,11 @@ processOptions() {
     fi
 }
 
+checkDocker () {
+    docker --version || errorExit "Unable to run docker"
+    docker-compose --version || errorExit "Unable to run docker-compose"
+}
+
 clean () {
     if [ "$CLEAN" == "true" ] && [ -d ${ROOT_DATA_DIR} ]; then
         local sure='n'
@@ -129,10 +135,10 @@ clean () {
 
 createDirectories () {
     if [ "$ACTION" == "start" ]; then
-        echo "Creating ${ROOT_DATA_DIR}"
+        echo "Preparing ${ROOT_DATA_DIR}"
         mkdir -p ${ROOT_DATA_DIR}/postgresql
         mkdir -p ${ROOT_DATA_DIR}/artifactory/etc
-        mkdir -p ${ROOT_DATA_DIR}/nginx/{conf.d,log,ssl}
+        mkdir -p ${ROOT_DATA_DIR}/nginx
     fi
 }
 
@@ -160,10 +166,15 @@ setDbPassword () {
 }
 
 getArtifactoryComposeYaml () {
-    if [ ! -f ${COMPOSE_FILE} ]; then
-        echo "Preparing ${COMPOSE_FILE}"
+    if [ ! -f ${COMPOSE_FILE} ] || [ "$FORCE_DOWNLOAD" == "true" ]; then
+        if [ -f ${COMPOSE_FILE} ] && [ "$FORCE_DOWNLOAD" == "true" ]; then
+            echo "Removing existing ${COMPOSE_FILE} before getting a new one"
+        fi
+
+        echo "Getting ${COMPOSE_FILE}"
         curl -# -o ${COMPOSE_FILE} ${ART_COMPOSE_YML} || errorExit "Getting ${DB_DRIVER} failed"
 
+        echo "Preparing ${COMPOSE_FILE}"
         # Do some editing
         sed -i.bkp -e "s,~/${DB_DRIVER},${ROOT_DATA_DIR}/${DB_DRIVER},g" ${COMPOSE_FILE} || errorExit "Updating $COMPOSE_FILE failed"
 
@@ -172,8 +183,6 @@ getArtifactoryComposeYaml () {
             sed -i.bkp -e "s,- ${LINUX_ROOT_DATA_DIR},- ${ROOT_DATA_DIR},g" ${COMPOSE_FILE} || errorExit "Updating $COMPOSE_FILE failed"
         fi
 
-        sed -i.bkp -e "s,nginx/conf.d/pro,nginx/conf.d,g" ${COMPOSE_FILE} || errorExit "Updating $COMPOSE_FILE failed"
-
         if [ -n "$TEMP_DB_PASSWORD" ]; then
             echo "Setting generated DB password"
             sed -i.bkp -e "s,=password,=${TEMP_DB_PASSWORD},g" ${COMPOSE_FILE} || errorExit "Updating $COMPOSE_FILE failed"
@@ -181,55 +190,11 @@ getArtifactoryComposeYaml () {
     fi
 }
 
-createDefaultArtifactoryConf () {
-    if [ "$ACTION" == "start" ] && [ ! -f ${ROOT_DATA_DIR}/nginx/conf.d/artifactory.conf ]; then
-        echo "Creating a default artifactory.conf"
-        cat << 'END_CONF' > ${ROOT_DATA_DIR}/nginx/conf.d/artifactory.conf
-## add ssl entries when https has been set in config
-ssl_certificate      /etc/nginx/ssl/example.pem;
-ssl_certificate_key  /etc/nginx/ssl/example.key;
-ssl_session_cache shared:SSL:1m;
-ssl_prefer_server_ciphers   on;
-## server configuration
-server {
-  listen 443 ssl;
-  listen 80 ;
-  server_name ~(?<repo>.+)\.artifactory artifactory;
-
-  if ($http_x_forwarded_proto = '') {
-    set $http_x_forwarded_proto  $scheme;
-  }
-  ## Application specific logs
-  ## access_log /var/log/nginx/artifactory-access.log timing;
-  ## error_log /var/log/nginx/artifactory-error.log;
-  rewrite ^/$ /artifactory/webapp/ redirect;
-  rewrite ^/artifactory/?(/webapp)?$ /artifactory/webapp/ redirect;
-  rewrite ^/(v1|v2)/(.*) /artifactory/api/docker/$repo/$1/$2;
-  chunked_transfer_encoding on;
-  client_max_body_size 0;
-  location /artifactory/ {
-    proxy_read_timeout  900;
-    proxy_pass_header   Server;
-    proxy_cookie_path   ~*^/.* /;
-    proxy_pass          http://artifactory:8081/artifactory/;
-    proxy_set_header    X-Artifactory-Override-Base-Url $http_x_forwarded_proto://$host:$server_port/artifactory;
-    proxy_set_header    X-Forwarded-Port  $server_port;
-    proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
-    proxy_set_header    Host              $http_host;
-    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
-  }
-}
-
-END_CONF
-
-    fi
-}
-
 validateActions () {
     case ${ACTION} in
         start)
             if [ "$(isDeployedAndCleanSet)" == "true" ]; then
-                errorExit "You cannot start and clean while system is already deployed. Stop and remove first."
+                errorExit "You cannot start and clean while system is already deployed. Stop and remove first ($SCRIPT_NAME -a remove -c)."
             fi
         ;;
         status)
@@ -238,17 +203,25 @@ validateActions () {
             fi
         ;;
         stop)
+            if [ "$(isDeployedAndCleanSet)" == "true" ]; then
+                errorExit "You cannot stop and clean while system is deployed. Remove it first ($SCRIPT_NAME -a remove -c)."
+            fi
         ;;
         restart)
             if [ "$(isDeployedAndCleanSet)" == "true" ]; then
                 errorExit "You cannot restart and clean while system is already deployed."
             fi
         ;;
+        upgrade)
+            if [ "$(isDeployedAndCleanSet)" == "true" ]; then
+                errorExit "You cannot upgrade and clean while system is already deployed."
+            fi
+        ;;
         remove)
         ;;
         logs)
             if [ "$(isDeployedAndCleanSet)" == "true" ]; then
-                errorExit "You cannot check docker logs and clean while system is already deployed."
+                errorExit "You cannot check logs and clean while system is already deployed."
             fi
         ;;
     esac
@@ -267,14 +240,41 @@ isDeployed () {
 }
 
 isDeployedAndCleanSet () {
-    if [ "$(isDeployed)" == "true" ] && [ "$CLEAN" == "true" ] ; then
+    if [ "$(isDeployed)" == "true" ] && [ "$CLEAN" == "true" ]; then
         echo -n "true"
     else
         echo -n "false"
     fi
 }
 
+optionalUpgrade () {
+    echo "Artifactory is already deployed"
+
+    local sure='n'
+
+    if [ "$FORCE" == "true" ]; then
+        sure='y'
+    else
+        read -p "Do you want to upgrade to the new version (${ARTIFACTORY_VERSION})? This will stop your Artifactory for the upgrade process [y/n]: " sure
+    fi
+
+    if [ "$sure" == "y" ]; then
+        FORCE_DOWNLOAD="true"
+        getArtifactoryComposeYaml
+        remove
+        start
+    else
+        echo "Aborting"
+        exit 1
+    fi
+}
+
 start () {
+    # If already deployed, this might be an upgrade
+    if [ "$(isDeployed)" == "true" ]; then
+        optionalUpgrade
+    fi
+
     echo "Starting Containers"
     docker-compose -f ${COMPOSE_FILE} up -d --remove-orphans
 }
@@ -295,9 +295,30 @@ restart () {
 }
 
 remove () {
-    stop
-    echo "Removing Containers"
-    docker-compose -f ${COMPOSE_FILE} rm --force
+    local sure='n'
+
+    if [ "$FORCE" == "true" ]; then
+        sure='y'
+    else
+        read -p "Are you sure you want to stop and remove Artifactory [y/n]: " sure
+    fi
+
+    if [ "$sure" == "y" ]; then
+        stop
+        echo "Removing Containers"
+        docker-compose -f ${COMPOSE_FILE} rm --force
+    else
+        echo "Aborting"
+        exit 1
+    fi
+}
+
+upgrade () {
+    if [ "$(isDeployed)" == "true" ]; then
+        optionalUpgrade
+    else
+        errorExit "There is no deployed Artifactory. Nothing to upgrade."
+    fi
 }
 
 logs () {
@@ -312,7 +333,7 @@ showMsg () {
         echo "Setup is complete."
         echo "Local directory $ROOT_DATA_DIR holds Artifactory, PostgreSQL and Nginx data and configurations."
         echo -e "$EXTRA_MSG"
-        echo "Point your browser to https://localhost/artifactory/ or http://localhost/artifactory/"
+        echo "Point your browser to https://<server>/artifactory/ or http://<server>/artifactory/"
         echo "########################################################################################################"
         echo
     fi
@@ -323,13 +344,13 @@ showMsg () {
 setOS
 validateSudo
 processOptions $*
+checkDocker
 validateActions
 clean
 createDirectories
 getDbDriver
 setDbPassword
 getArtifactoryComposeYaml
-createDefaultArtifactoryConf
 
 eval ${ACTION}
 
